schemata:
  <keyspace_name>:
    definition: <keyspace_definition>
    tables:
      <table_name>:
        definition: <table_definition>
        distributions:          # optional
          <column_name>: <generator_args>
          <column_name>: <generator_args>
          ...
      <table_name>:
        definition: <table_definition>
  <keyspace_name>:
    definition: <keyspace_definition>
    tables:
      ...

workloads:
  <workload_name>:
    queries:
      - query: <query>
        chance: <value>         # only needed if query type is 'insert'
      - query: <query>
      ...
    ratio: <value>
  <workload_name>:
    queries:
      ...

config:
  database:
      type: <databas_type>
      connection arguments: <connection_arguments>
  termination conditions:
    latency:
      max: 1000 # Value in ms
      consecutive: 5
    queries:
      max: 10000 # bonus parameter
      consecutive: 5